/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mZ6Y3tA2Uv2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ideasubmit() {
  const [idea, setIdea] = useState("")
  const handleSubmit = (e) => {
    e.preventDefault()
    router.push(`/idea-evaluation?idea=${encodeURIComponent(idea)}`)
  }
  const autoTypeIdeas = [
    "Develop a mobile app that helps users track their daily water intake",
    "Create an AI-powered virtual assistant to help small businesses with administrative tasks",
    "Design a platform that connects local artisans with customers around the world",
    "Build a social network for pet owners to connect and share tips",
    "Create an online marketplace for handmade sustainable home goods",
    "Develop a smart home system that integrates with renewable energy sources",
  ]
  const handleAutoIdeaClick = (autoIdea) => {
    setIdea(autoIdea)
  }
  return (
    <div className="flex flex-col w-full min-h-screen bg-muted/40">
      <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Breadcrumb className="hidden md:flex">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="#" prefetch={false}>
                  Home
                </Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Submit Idea</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </header>
      <main className="flex-1 flex items-center justify-center p-4 sm:px-6 sm:py-0">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Submit Your Idea</CardTitle>
            <CardDescription>
              Enter a brief description of your idea below and get feedback from our community.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <Textarea
                placeholder="Describe your idea..."
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                className="min-h-[100px]"
              />
              <Button type="submit">Submit Idea</Button>
            </form>
          </CardContent>
        </Card>
      </main>
      <section className="flex flex-col items-center gap-4 px-4 sm:px-6 mt-8">
        <h3 className="text-lg font-medium">Explore More Ideas:</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          {autoTypeIdeas.map((autoIdea, index) => (
            <div
              key={index}
              className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4"
              onClick={() => handleAutoIdeaClick(autoIdea)}
            >
              <h4 className="text-lg font-medium mb-2">{autoIdea.slice(0, 40)}...</h4>
              <p className="text-sm text-muted-foreground line-clamp-3">{autoIdea}</p>
            </div>
          ))}
        </div>
      </section>
      <section className="flex flex-col items-center gap-4 px-4 sm:px-6 mt-8">
        <h3 className="text-lg font-medium">Popular Ideas:</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">AI-powered personal assistant</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Develop an AI-powered virtual assistant that can help users with a wide range of tasks, from scheduling
              appointments to managing finances and more.
            </p>
          </div>
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">Sustainable fashion marketplace</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Create an online platform that connects eco-conscious consumers with ethical and sustainable fashion
              brands, promoting a more responsible approach to clothing.
            </p>
          </div>
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">Smart home energy management</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Develop a comprehensive smart home system that integrates with renewable energy sources, allowing users to
              optimize their energy consumption and reduce their carbon footprint.
            </p>
          </div>
        </div>
      </section>
      <section className="flex flex-col items-center gap-4 px-4 sm:px-6 mt-8">
        <h3 className="text-lg font-medium">Trending Ideas:</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">Peer-to-peer skills exchange</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Create a platform that allows users to exchange their skills and expertise with others, fostering a
              collaborative community and promoting lifelong learning.
            </p>
          </div>
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">Augmented reality shopping</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Develop an AR-powered shopping experience that allows customers to virtually try on products, visualize
              them in their own spaces, and make more informed purchasing decisions.
            </p>
          </div>
          <div className="bg-background rounded-md shadow-sm hover:bg-muted/50 cursor-pointer p-4">
            <h4 className="text-lg font-medium mb-2">Personalized nutrition coaching</h4>
            <p className="text-sm text-muted-foreground line-clamp-3">
              Create an AI-driven platform that provides personalized nutrition and wellness plans, helping users
              achieve their health goals through tailored guidance and support.
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}
